### ISSUE TITLE
Slack Preset

### ISSUE THREAD

**Issue by dyoder** [dashkite/genie-presets#1]
This would introduce a single task: `slack:configure` which would set up a GitHub action, like we do for ReType.

We need to create the action, which would be to send a message based on the release. The code to call Slack is straightforward:

```coffeescript
import { WebClient as SlackWebClient } from "@slack/web-api"

client = new SlackWebClient process.env.SLACK_APP_TOKEN

export default (genie) ->
  genie.define "slack:test", ->
    client.chat.postMessage
      channel: "releases"
      text: "Testing 1-2-3"
```

Setting up the action is also [straightforward](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action) but does require bundling the code.

From there it can be referenced in an action, which would look something like:

```yaml
name: Post a message to Slack when a release is tagged.
on:
  workflow_dispatch:
  release:
    branches:
      - main
    types:
      - released

jobs:
  name: Post release message to Slack.
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: retypeapp/action-build@v1
      with:
        license: ${{ secrets.SLACK_APP_TOKEN }}
```

This would work well enough for our purposes, but it wouldn't work for anyone else because you need to add the app token to your organization's secrets. I'm a bit unclear on how you'd make this work without introducing an API, but perhaps that's the more general solution. In turn, that makes me wonder a bit if maybe this would just be better using a third-party CI/CD tool.
